### ISSUE TITLE
About memory usage

### ISSUE THREAD

**Issue by baoqianyue** [AcherStyx/CoCap#1]
Hello, thank you very much for publishing such a high-level code. When I use your code to run on my personal video dataset, the memory usage of the program is very high, but the RAM of the workstation I use is 128GB. Of course, this may also be related to the size of my video. Is there any way to reduce the RAM of the code by modifying the config?

**Comment by Yaojie-Shen** [comment]
Hi!
By default, the configuration is set to run on an 8-card V100 machine with 96 CPU cores.To ensure optimal loading speed, I've configured the `num_workers` to be 96/8=12. This way, each CPU core will have its own decode thread. 

You can adjust this value in `configs/compressed_video/base.yaml`. Feel free to override it in your custom configuration files, such as `configs/compressed_video/msrvtt_captioning.yaml`, or through the command line as shown here: `python3 mm_video/run_net.py --cfg configs/compressed_video/msrvtt_captioning.yaml DATA.LOADER.NUM_WORKERS=4`.

Please keep in mind that altering this value may impact the data loader’s speed, so be sure to monitor your GPU’s utilization while making adjustments. 👀

**Comment by baoqianyue** [comment]
Thank you very much. The problem has been solved. I will try to replace the machine with better specifications to speed up data reading.
