### ISSUE TITLE
AssertionError: An object named 'MSRVTTCaptioningDatasetForCLIP' was already registered in 'DATASET' registry!

### ISSUE THREAD

**Issue by tjumc** [AcherStyx/CoCap#11]
Hello! Thank you for your contribution. 
I have a problem when training, here is the error log:

![image](https://github.com/acherstyx/CoCap/assets/67730345/a70e4479-684c-4822-85fb-68da723447c6)

Looking forward to your reply.

**Comment by Yaojie-Shen** [comment]
This error indicates that you are trying to register a dataset named "MSRVTTCaptionDatasetForCLIP" more than once. You should rename the dataset to another name and remove duplicates.

**Comment by tjumc** [comment]
Thanks for your early reply, I modified the regist function in the fvcore.py file to avoid registering duplicate registrations.
Then a new problem occurred: 

> KeyError: "No object named 'CoCap' found in 'MODEL' registry!"

But I checked the log file and found "CoCap" in the "MODEL" registry.

![image](https://github.com/acherstyx/CoCap/assets/67730345/7fb0b928-7d1b-4fd4-9d4b-4fd44e41983e)
