### ISSUE TITLE
ERROR about cv_reader when using MSVD

### ISSUE THREAD

**Issue by tjumc** [AcherStyx/CoCap#12]
![image](https://github.com/acherstyx/CoCap/assets/67730345/9f0b4090-f2f5-4f51-9166-e519ac70f5b2)

I converted the video according to the method you provided. I found that some errors occurred in the batch of videos（num_workers=12, 4 were correct and 8 were wrong) , the wrong videos are:

```
./dataset/msvd/videos_240_h264_keyint_60/Nd45qJn61Dw_0_10.avi
./dataset/msvd/videos_240_h264_keyint_60/5P6UU6m3cqk_57_75.avi
./dataset/msvd/videos_240_h264_keyint_60/PD6eQY7yCfw_32_37.avi
./dataset/msvd/videos_240_h264_keyint_60/77iDIp40m9E_159_181.avi
./dataset/msvd/videos_240_h264_keyint_60/9Wr48VFhZH8_45_50.avi
./dataset/msvd/videos_240_h264_keyint_60/HxRK-WqZ5Gk_30_50.avi
./dataset/msvd/videos_240_h264_keyint_60/UgUFP5baQ9Y_0_7.avi
./dataset/msvd/videos_240_h264_keyint_60/PqSZ89FqpiY_65_75.avi
```

and I converted these wrong videos to mp4 but got the same error.

I wonder if there is something wrong with the MSVD dataset or cv_reader (I can train normally on MSRVTT).

Your help will be greatly appreciated.

**Comment by Zeyu1226-mt** [comment]
> ![image](https://private-user-images.githubusercontent.com/67730345/318845654-9f0b4090-f2f5-4f51-9166-e519ac70f5b2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM1NjM5NzksIm5iZiI6MTcyMzU2MzY3OSwicGF0aCI6Ii82NzczMDM0NS8zMTg4NDU2NTQtOWYwYjQwOTAtZjJmNS00ZjUxLTkxNjYtZTUxOWFjNzBmNWIyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODEzVDE1NDExOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdjNTEyMTFiM2ZmYzg4YzQzMDE3ZWI4YTNlYTlkMTNiMjk1ZGJjYzEyNTRiNjY5ZGI1Y2M3ZWNlYTgxMTA4MzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.M9eb6AxyO5cmkdGICxlgDAecZKkemK8Qyipp5EmdPNg)
> 
> I converted the video according to the method you provided. I found that some errors occurred in the batch of videos（num_workers=12, 4 were correct and 8 were wrong) , the wrong videos are:
> 
> ```
> ./dataset/msvd/videos_240_h264_keyint_60/Nd45qJn61Dw_0_10.avi
> ./dataset/msvd/videos_240_h264_keyint_60/5P6UU6m3cqk_57_75.avi
> ./dataset/msvd/videos_240_h264_keyint_60/PD6eQY7yCfw_32_37.avi
> ./dataset/msvd/videos_240_h264_keyint_60/77iDIp40m9E_159_181.avi
> ./dataset/msvd/videos_240_h264_keyint_60/9Wr48VFhZH8_45_50.avi
> ./dataset/msvd/videos_240_h264_keyint_60/HxRK-WqZ5Gk_30_50.avi
> ./dataset/msvd/videos_240_h264_keyint_60/UgUFP5baQ9Y_0_7.avi
> ./dataset/msvd/videos_240_h264_keyint_60/PqSZ89FqpiY_65_75.avi
> ```
> 
> and I converted these wrong videos to mp4 but got the same error.
> 
> I wonder if there is something wrong with the MSVD dataset or cv_reader (I can train normally on MSRVTT).
> 
> Your help will be greatly appreciated.

Hello, i met the same problem on MSVD dataset. Do you solve this problem?? How to solve this problem??

**Comment by Zeyu1226-mt** [comment]
> ![image](https://private-user-images.githubusercontent.com/67730345/318845654-9f0b4090-f2f5-4f51-9166-e519ac70f5b2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM2MTQ0ODMsIm5iZiI6MTcyMzYxNDE4MywicGF0aCI6Ii82NzczMDM0NS8zMTg4NDU2NTQtOWYwYjQwOTAtZjJmNS00ZjUxLTkxNjYtZTUxOWFjNzBmNWIyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE0VDA1NDMwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRhZTY2Y2FkNzZhNzUxMjhiNTkxNTNkODQxZjE4ZDEzODEzNjMzZTJiZTdmYTE3Y2VlNTM4ZmJhMDMyYjVlZjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.FJ2yZ98rWd-juB9iK8ZqB4D9ErQxO2JqwTNZc3t8EaY)
> 
> I converted the video according to the method you provided. I found that some errors occurred in the batch of videos（num_workers=12, 4 were correct and 8 were wrong) , the wrong videos are:
> 
> ```
> ./dataset/msvd/videos_240_h264_keyint_60/Nd45qJn61Dw_0_10.avi
> ./dataset/msvd/videos_240_h264_keyint_60/5P6UU6m3cqk_57_75.avi
> ./dataset/msvd/videos_240_h264_keyint_60/PD6eQY7yCfw_32_37.avi
> ./dataset/msvd/videos_240_h264_keyint_60/77iDIp40m9E_159_181.avi
> ./dataset/msvd/videos_240_h264_keyint_60/9Wr48VFhZH8_45_50.avi
> ./dataset/msvd/videos_240_h264_keyint_60/HxRK-WqZ5Gk_30_50.avi
> ./dataset/msvd/videos_240_h264_keyint_60/UgUFP5baQ9Y_0_7.avi
> ./dataset/msvd/videos_240_h264_keyint_60/PqSZ89FqpiY_65_75.avi
> ```
> 
> and I converted these wrong videos to mp4 but got the same error.
> 
> I wonder if there is something wrong with the MSVD dataset or cv_reader (I can train normally on MSRVTT).
> 
> Your help will be greatly appreciated.

I find that it can run normally on MSRVTT.  Does the MSVD dataset have some problems?

**Comment by tjumc** [comment]
并没有得到解决，所以我只做了MSRVTT的实验o(╥﹏╥)o

> > ![image](https://private-user-images.githubusercontent.com/67730345/318845654-9f0b4090-f2f5-4f51-9166-e519ac70f5b2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM2MTQ0ODMsIm5iZiI6MTcyMzYxNDE4MywicGF0aCI6Ii82NzczMDM0NS8zMTg4NDU2NTQtOWYwYjQwOTAtZjJmNS00ZjUxLTkxNjYtZTUxOWFjNzBmNWIyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE0VDA1NDMwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRhZTY2Y2FkNzZhNzUxMjhiNTkxNTNkODQxZjE4ZDEzODEzNjMzZTJiZTdmYTE3Y2VlNTM4ZmJhMDMyYjVlZjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.FJ2yZ98rWd-juB9iK8ZqB4D9ErQxO2JqwTNZc3t8EaY)
> > I converted the video according to the method you provided. I found that some errors occurred in the batch of videos（num_workers=12, 4 were correct and 8 were wrong) , the wrong videos are:
> > ```
> > ./dataset/msvd/videos_240_h264_keyint_60/Nd45qJn61Dw_0_10.avi
> > ./dataset/msvd/videos_240_h264_keyint_60/5P6UU6m3cqk_57_75.avi
> > ./dataset/msvd/videos_240_h264_keyint_60/PD6eQY7yCfw_32_37.avi
> > ./dataset/msvd/videos_240_h264_keyint_60/77iDIp40m9E_159_181.avi
> > ./dataset/msvd/videos_240_h264_keyint_60/9Wr48VFhZH8_45_50.avi
> > ./dataset/msvd/videos_240_h264_keyint_60/HxRK-WqZ5Gk_30_50.avi
> > ./dataset/msvd/videos_240_h264_keyint_60/UgUFP5baQ9Y_0_7.avi
> > ./dataset/msvd/videos_240_h264_keyint_60/PqSZ89FqpiY_65_75.avi
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > and I converted these wrong videos to mp4 but got the same error.
> > I wonder if there is something wrong with the MSVD dataset or cv_reader (I can train normally on MSRVTT).
> > Your help will be greatly appreciated.
> 
> I find that it can run normally on MSRVTT. Does the MSVD dataset have some problems?

**Comment by Xiyu-AI** [comment]
可以加个微信吗？我也是研究字幕生成的，我也有一些伙伴在群里，要不要一起加个群，以后大家可以一起讨论下？



发自我的iPhone


------------------ Original ------------------
From: Mc ***@***.***&gt;
Date: Wed,Aug 14,2024 2:17 PM
To: acherstyx/CoCap ***@***.***&gt;
Cc: 习泽宇 ***@***.***&gt;, Comment ***@***.***&gt;
Subject: Re: [acherstyx/CoCap] ERROR about cv_reader when using MSVD (Issue#12)

**Comment by Yaojie-Shen** [comment]
Refer to https://github.com/acherstyx/CoCap/issues/13.
