### ISSUE TITLE
复现问题

### ISSUE THREAD

**Issue by shearu** [AcherStyx/CoCap#15]
您好，您的代码我尝试跑了MSVD数据集ViTB16预训练参数，结果4项指标只比您论文中ViTL14的差一点点，这可能是什么原因呢

**Comment by Yaojie-Shen** [comment]
> 您好，您的代码我尝试跑了MSVD数据集ViTB16预训练参数，结果4项指标只比您论文中ViTL14的差一点点，这可能是什么原因呢

Hi，我想这是正常的，我们在完成代码整理并release之后也重新跑了一遍训练，并且同样发现性能比原来paper中report的结果有了提升。我们猜测主要是因为论文中结果对应的版本在设置学习率的分组的时候有点问题（code is [here](https://github.com/acherstyx/CoCap/blob/c42d593de3f29f7b2579e0daf1b70e490ecb9bcf/mm_video/trainer/cocap_trainer.py#L72)），而我们在最后整理代码时fix了这里的一些问题。

**Comment by Yaojie-Shen** [comment]
没有进一步问题的话我先close了
