### ISSUE TITLE
Problem of Prepare data  

### ISSUE THREAD

**Issue by xyc0833** [AcherStyx/CoCap#16]
不好意思 想请教一下 在Data Preparation部分的第三步3. Convert and Crop the Videos 执行python3 tools/video_convert.py --codec=libx264 --keyint=60 --resize=240 -i dataset/msvd/videos -o dataset/msvd/videos_240_h264_keyint_60 --verbose 这个命令的时候出现报错
![image](https://github.com/user-attachments/assets/9c0a9410-c84f-439d-b0bb-5e9d997357ad)
想请教一下 这个问题应该如何解决 （ffmpeg已经按照要求安装了5.1的版本）
![image](https://github.com/user-attachments/assets/05443233-c8bd-4360-a280-b1696d7e8ddf)
原始文件中也放入了对应的视频（虽然视频没有放全部的）
![image](https://github.com/user-attachments/assets/bc8ae73a-a985-4252-ae3f-fa2d7f03a7fa)
（之前用msrvtt的视频也是类似的问题 命令行能正确输出 但是对应output的文件夹videos_240_h264_keyint_60里面内容是空的 加入了--verbose命令之后也是这个问题） 求教 感恩感谢

**Comment by xyc0833** [comment]
解决方案：video.py文件里面 按照下面的方式改一下  第66行
![image](https://github.com/user-attachments/assets/75c32912-b6cf-4b3f-9bcb-19a603890d11)
mm_video/utils/video.py

**Comment by tjumc** [comment]
你好，我在执行vatex数据集的命令时，同样遇到了"vatex/videos_240_h264_keyint_60"文件夹中没有保存文件的问题，我尝试了你的方法进行了如下修改：
` command = ["sudo", ffmpeg_exec, "-i", f"{input_file}"]`
` # command = ["sudo", ffmpeg_exec, "-i", f"{input_file}", "-max_muxing_queue_size", "9999"]`

然而还是没有作用，请问你遇到了这样的问题了吗？

**Comment by Yaojie-Shen** [comment]
> 你好，我在执行vatex数据集的命令时，同样遇到了"vatex/videos_240_h264_keyint_60"文件夹中没有保存文件的问题，我尝试了你的方法进行了如下修改： ` command = ["sudo", ffmpeg_exec, "-i", f"{input_file}"]` ` # command = ["sudo", ffmpeg_exec, "-i", f"{input_file}", "-max_muxing_queue_size", "9999"]`
> 
> 然而还是没有作用，请问你遇到了这样的问题了吗？

Hi @NCU-MC , 你有尝试加上`--verbose`参数吗，可以看一下ffmpeg有什么报错。因为输出太多了，所以默认把ffmpeg的输出都重定向到了`/dev/null`。

**Comment by tjumc** [comment]
> > 你好，我在执行vatex数据集的命令时，同样遇到了"vatex/videos_240_h264_keyint_60"文件夹中没有保存文件的问题，我尝试了你的方法进行了如下修改： ` command = ["sudo", ffmpeg_exec, "-i", f"{input_file}"]` ` # command = ["sudo", ffmpeg_exec, "-i", f"{input_file}", "-max_muxing_queue_size", "9999"]`
> > 然而还是没有作用，请问你遇到了这样的问题了吗？
> 
> Hi @NCU-MC , 你有尝试加上`--verbose`参数吗，可以看一下ffmpeg有什么报错。因为输出太多了，所以默认把ffmpeg的输出都重定向到了`/dev/null`。

感谢您的解答，我加上了`--verbose`参数，报错信息为：“sudo: Compressed-Video-Reader/ffmpeg：找不到命令”，之后我在`Compressed-Video-Reader`路径下直接输入`ffmpeg --version`命令，同样提示找不到ffmpeg。
在准备工作中，我按照[这里](https://github.com/acherstyx/Compressed-Video-Reader/tree/main)的步骤成功安装了cv_reader，在Compressed-Video-Reader/ffmpeg路径下有如下文件：
![image](https://github.com/user-attachments/assets/4c14836a-ed3e-4c8f-b032-19e2d591087b)
难道是安装过程出了什么问题吗？

**Comment by Yaojie-Shen** [comment]
> > > 你好，我在执行vatex数据集的命令时，同样遇到了"vatex/videos_240_h264_keyint_60"文件夹中没有保存文件的问题，我尝试了你的方法进行了如下修改： ` command = ["sudo", ffmpeg_exec, "-i", f"{input_file}"]` ` # command = ["sudo", ffmpeg_exec, "-i", f"{input_file}", "-max_muxing_queue_size", "9999"]`
> > > 然而还是没有作用，请问你遇到了这样的问题了吗？
> > 
> > 
> > Hi @NCU-MC , 你有尝试加上`--verbose`参数吗，可以看一下ffmpeg有什么报错。因为输出太多了，所以默认把ffmpeg的输出都重定向到了`/dev/null`。
> 
> 感谢您的解答，我加上了`--verbose`参数，报错信息为：“sudo: Compressed-Video-Reader/ffmpeg：找不到命令”，之后我在`Compressed-Video-Reader`路径下直接输入`ffmpeg --version`命令，同样提示找不到ffmpeg。 在准备工作中，我按照[这里](https://github.com/acherstyx/Compressed-Video-Reader/tree/main)的步骤成功安装了cv_reader，在Compressed-Video-Reader/ffmpeg路径下有如下文件： ![image](https://private-user-images.githubusercontent.com/67730345/400143798-4c14836a-ed3e-4c8f-b032-19e2d591087b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzYwMDA2MzgsIm5iZiI6MTczNjAwMDMzOCwicGF0aCI6Ii82NzczMDM0NS80MDAxNDM3OTgtNGMxNDgzNmEtZWQzZS00YzhmLWIwMzItMTllMmQ1OTEwODdiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAxMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMTA0VDE0MTg1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkyYzliNmQyNDRlMDJjNDU0NjQzNmRmNjZmZmIzODA2OGU3ZDA4Y2FhZDg4YzliYzBlMGViMTdjODU1MTBkN2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.wS6Qr1fLsBxQbDp9j7p13ChZc3xfT98l-DMw8AL76ug) 难道是安装过程出了什么问题吗？

`cv_reader` 安装好后并不会有 ffmpeg，实际上我也不建议把 `cv_reader` 里面的ffmpeg装进去（从[这里](https://github.com/acherstyx/Compressed-Video-Reader/blob/2a4fc74f9e18bdc6aea68c7fb14f4388551d2ad8/ffmpeg/install_ffmpeg.sh#L57)你可以看到，实际上指向了一个项目下的子文件夹。所以下面虽然有`make install`命令，但是只是安装到了项目的子目录下面），因为这个ffmpeg是打过补丁，用来读取residual的。静态链接编译出来的ffmpeg会和其他的代码一起作为python模块安装。

转格式的时候你需要额外安装一个ffmpeg，例如直接用系统的包管理安装，最好是新一点的版本（5.x差不多）以保证能正确读取所有的视频。

**Comment by tjumc** [comment]
> > > > 你好，我在执行vatex数据集的命令时，同样遇到了"vatex/videos_240_h264_keyint_60"文件夹中没有保存文件的问题，我尝试了你的方法进行了如下修改： ` command = ["sudo", ffmpeg_exec, "-i", f"{input_file}"]` ` # command = ["sudo", ffmpeg_exec, "-i", f"{input_file}", "-max_muxing_queue_size", "9999"]`
> > > > 然而还是没有作用，请问你遇到了这样的问题了吗？
> > > 
> > > 
> > > Hi @NCU-MC , 你有尝试加上`--verbose`参数吗，可以看一下ffmpeg有什么报错。因为输出太多了，所以默认把ffmpeg的输出都重定向到了`/dev/null`。
> > 
> > 
> > 感谢您的解答，我加上了`--verbose`参数，报错信息为：“sudo: Compressed-Video-Reader/ffmpeg：找不到命令”，之后我在`Compressed-Video-Reader`路径下直接输入`ffmpeg --version`命令，同样提示找不到ffmpeg。 在准备工作中，我按照[这里](https://github.com/acherstyx/Compressed-Video-Reader/tree/main)的步骤成功安装了cv_reader，在Compressed-Video-Reader/ffmpeg路径下有如下文件： ![image](https://private-user-images.githubusercontent.com/67730345/400143798-4c14836a-ed3e-4c8f-b032-19e2d591087b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzYwMDA2MzgsIm5iZiI6MTczNjAwMDMzOCwicGF0aCI6Ii82NzczMDM0NS80MDAxNDM3OTgtNGMxNDgzNmEtZWQzZS00YzhmLWIwMzItMTllMmQ1OTEwODdiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAxMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMTA0VDE0MTg1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkyYzliNmQyNDRlMDJjNDU0NjQzNmRmNjZmZmIzODA2OGU3ZDA4Y2FhZDg4YzliYzBlMGViMTdjODU1MTBkN2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.wS6Qr1fLsBxQbDp9j7p13ChZc3xfT98l-DMw8AL76ug) 难道是安装过程出了什么问题吗？
> 
> `cv_reader` 安装好后并不会有 ffmpeg，实际上我也不建议把 `cv_reader` 里面的ffmpeg装进去（从[这里](https://github.com/acherstyx/Compressed-Video-Reader/blob/2a4fc74f9e18bdc6aea68c7fb14f4388551d2ad8/ffmpeg/install_ffmpeg.sh#L57)你可以看到，实际上指向了一个项目下的子文件夹。所以下面虽然有`make install`命令，但是只是安装到了项目的子目录下面），因为这个ffmpeg是打过补丁，用来读取residual的。静态链接编译出来的ffmpeg会和其他的代码一起作为python模块安装。
> 
> 转格式的时候你需要额外安装一个ffmpeg，例如直接用系统的包管理安装，最好是新一点的版本（5.x差不多）以保证能正确读取所有的视频。

我单独安装了ffmpeg，解决了问题。感谢您的帮助与解答！
