### ISSUE TITLE
The issue regarding the code getting stuck in the process.

### ISSUE THREAD

**Issue by luoyewuhen88** [AcherStyx/CoCap#2]
Hello, thank you very much for your open-source code. I've been working on reproducing your code recently and applying it to my personal dataset. However, I've encountered an issue where the process gets stuck after completing one epoch, with no error reported. I hope to get your help. Thank you very much!

**Comment by luoyewuhen88** [comment]
Additionally, I would like to know if this warning message is the cause of the issue mentioned above. If so, how can it be resolved? Thank you!
WARNING : Meter is not specified!

**Comment by Yaojie-Shen** [comment]
> Additionally, I would like to know if this warning message is the cause of the issue mentioned above. If so, how can it be resolved? Thank you! WARNING : Meter is not specified!

Hi, thank you for your interest in our work.
This warning is nothing important. You can just ignore it if you do not want to use any meter for monitoring. Currently, based on your description, I have no idea where the problem is occurring.

My suggestion is:
1. Check the `logging_debug.txt` to see where your training gets stuck. You can also insert more debug output to identify the issue.
2. Check if your machine is running out of memory. The decoded video data is memory-consuming, and sometimes the Torch data loader worker might get killed, causing a hang.

That's what I could think of based on the limited information. Please provide more details if you are still experiencing the same problem.

**Comment by luoyewuhen88** [comment]
> > 此外，我想知道此警告消息是否是上述问题的原因。如果是的话，该如何解决呢？谢谢你！警告：未指定仪表！
> 
> 您好，感谢您对我们工作的兴趣。 这个警告并不重要。如果您不想使用任何仪表进行监控，则可以忽略它。目前，根据您的描述，我不知道问题出在哪里。
> 
> 我的建议是：
> 
> 1. 检查一下`logging_debug.txt`你的训练在哪里被卡住了。您还可以插入更多调试输出来识别问题。
> 2. 检查您的机器是否内存不足。解码的视频数据非常消耗内存，有时 Torch 数据加载器工作线程可能会被杀死，从而导致挂起。
> 
> 根据有限的信息，我能想到的就是这些。如果您仍然遇到同样的问题，请提供更多详细信息。

Thank you for your response. My current hardware setup includes four RTX 3090 GPUs. I would like to know if there is a significant transfer of weight parameters between the completion of one epoch and the start of the next epoch. Do I need to make additional settings based on my hardware configuration before starting the next epoch?Meanwhile, here is some troubleshooting information. The terminal output is stuck at the position shown in the image, and I suspect there might be an issue with `_before_train_epoch()`. I hope to receive more assistance from you. Thank you!
![QQ图片20231027100138](https://github.com/AcherStyx/CoCap/assets/137153111/35881df1-19f3-4e4c-83c3-2a587b049f0d)

**Comment by Yaojie-Shen** [comment]
> Thank you for your response. My current hardware setup includes four RTX 3090 GPUs. I would like to know if there is a significant transfer of weight parameters between the completion of one epoch and the start of the next epoch. Do I need to make additional settings based on my hardware configuration before starting the next epoch?Meanwhile, here is some troubleshooting information. The terminal output is stuck at the position shown in the image, and I suspect there might be an issue with `_before_train_epoch()`. I hope to receive more assistance from you. Thank you! ![QQ图片20231027100138](https://user-images.githubusercontent.com/137153111/278518766-35881df1-19f3-4e4c-83c3-2a587b049f0d.png)

It appears that you are using Torch's distributed data parallel with four GPUs, as indicated by the "第0次_on_train_epoch" being printed four times. However, in the second epoch, only three threads entered and printed "_before_train_epoch()" and "进入判断" to the stdout. This discrepancy might be causing the issue. It seems that the training loop on one rank hasn't finished, leading to the barrier at: https://github.com/AcherStyx/CoCap/blob/c42d593de3f29f7b2579e0daf1b70e490ecb9bcf/mm_video/trainer/build.py#L132 causing them to get stuck. You should verify that the data loader at these four ranks has the same length and that the distributed data sampler is correctly applied to each of them.

**Comment by Yaojie-Shen** [comment]
Closing this issue as it has been inactive for a few days. Please feel free to reopen it if you encounter this problem again or have any other concerns.
