### ISSUE TITLE
How can I use the pretrained checkpoints?

### ISSUE THREAD

**Issue by Stanly-19** [AcherStyx/CoCap#5]
Thanks to your work!
Could you please tell me how can I use the checkpoints you released?

**Comment by Yaojie-Shen** [comment]
Hi!
The model is constructed at [model.py L28](https://github.com/acherstyx/CoCap/blob/c42d593de3f29f7b2579e0daf1b70e490ecb9bcf/mm_video/modeling/model.py#L28C10-L28C10) based on the configs. To initiate the model, utilize the configurations specified in the configs/compressed_video directory and subsequently load the corresponding checkpoint.
If your want to resume from a specific checkpoint and evaluate on the test split, you should: 
1. Set `TRAINER.TRAINER_BASE.RESUME` to the path of the checkpoint.
2. Disable training by setting `TRAINER.TRAINER_BASE.TRAIN_ENABLE` to False.
