### ISSUE TITLE
Inference Script

### ISSUE THREAD

**Issue by pribadihcr** [AcherStyx/CoCap#7]
hi @acherstyx,

Is there an inference script to demo?

Thanks

**Comment by Yaojie-Shen** [comment]
> hi @acherstyx,
> 
> Is there an inference script to demo?
> 
> Thanks

Hello @pribadihcr !

We are sorry that we haven't provide any demo yet. Currently, you can conduct an evaluation by setting `TRAINER.TRAINER_BASE.TRAIN_ENABLE` to `False` and `TRAINER.TRAINER_BASE.TEST_ENABLE` to `True`, although it may not be exactly the same things.
For example:

```bash
python3 mm_video/run_net.py --cfg configs/compressed_video/msrvtt_captioning.yaml TRAINER.TRAINER_BASE.TRAIN_ENABLE False TRAINER.TRAINER_BASE.TEST_ENABLE True
```

The test stage is similar to inference, the difference is that the inputs are built by the dataset.
Please let us know if you encounter any other issues. 

Thanks!
